### PR TITLE
Fix rusb callbacks for macOS 12.4

### LINKED ISSUE #104: rusb callbacks never hit on macOS 12.4
The `device_arrived` and `device_left` callbacks are never hit for me on macOS 12.4.

### PR DESCRIPTION
**Pull request by rajohns08**
Fixes #104

### CODE REVIEW

**Comment by leodag** [comment]
I'm on Linux, and was not getting any device connected/disconnected events. This fixed it. Thanks!

**Comment by leodag** [comment]
By the way, instead of doing `unsafe impl Send for PnPDetectLibusb`, the `UsbCallback` can be changed to be `Send` doing `pub trait UsbCallback: Send`

**Comment by jabl** [comment]
Now that I look at this one, it's very similar to my PR https://github.com/haimgel/display-switch/pull/111 that I just submitted a few hours ago, except I did made the UsbCallback Send as suggested above.

**Comment by haimgel** [comment]
@jabl I think #111 is a bit better, so closing this one since #111 is merged.

**Pull request closed without merging**
